language: php 

php: 
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests/BinaryParseTest.php
  - vendor/bin/phpunit tests/BinaryParseTest.php
  - vendor/bin/phpunit tests/ParseXMLTest.php
  - vendor/bin/phpunit tests/WriteBinaryTest.php
  - vendor/bin/phpunit tests/WriteXMLTest.php


cache:
  directories:
    - "$HOME/.composer/cache"
